### ISSUE TITLE
Allow users to access and modify only their own user profiles

### ISSUE THREAD

**Issue by arnellebalane** [blkflower/transtrack-backend#16]
The user ID should be determined from the current user session instead of being passed as part of the request. This makes the API secure by allowing changes to the user profile to be made only by the user that the user profile belongs to.

https://github.com/blkflower/pitaka-backend/blob/02adebd3c1d8b7b8f992e7a6896d8fce1f2629e4/src/modules/user/adapter/controller/user-profile.controller.ts#L13-L23

**Comment by PCalape** [comment]
Hello @arnellebalane! As for this one the authenticated user id is not passed via the API request but instead it is taken from the backend via the supabase strategy. Therefore it is currently safe and user is only able to edit his own profile. As discussed, tagging this one as closed. Thanks!
